zones:
- zone_id: '1780396737340'
  strip_id: 2
  start_along: 0.6
  end_along: 1
  mission_type: plant
  target: naut
  status: completed
- zone_id: '1780398080991'
  strip_id: 1
  start_along: 1.6
  end_along: 1.8
  mission_type: plant
  target: naut
  status: completed
- zone_id: test_zone_new
  strip_id: 0
  start_along: 2
  end_along: 2.8
  mission_type: plant
  target: naut
  status: planned
- zone_id: '1780496194277'
  strip_id: 2
  start_along: 2.4
  end_along: 2.5
  mission_type: plant
  target: naut
  status: planned
- zone_id: '1780551257379'
  strip_id: 3
  start_along: 0.9
  end_along: 1.1
  mission_type: plant
  target: naut
  status: planned
